
name: Deploy to GitHub Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Generate unique timestamp for cache busting
        id: timestamp
        run: echo "DEPLOY_TIMESTAMP=$(date +%s%N)" >> $GITHUB_ENV
        
      - name: Build
        run: npm run build
        env:
          # Enhanced cache busting with unique timestamp
          VITE_CACHE_BUSTER: ${{ github.sha }}_${{ github.run_number }}_${{ env.DEPLOY_TIMESTAMP }}
        
      # Create 404.html for SPA routing
      - name: Create 404.html
        run: |
          cat > ./dist/404.html << 'EOL'
          <!DOCTYPE html>
          <html>
            <head>
              <meta charset="utf-8">
              <title>Orthodox Echoes - Page Not Found</title>
              <script type="text/javascript">
                var pathSegmentsToKeep = 1;
                var l = window.location;
                l.replace(
                  l.protocol + '//' + l.hostname + (l.port ? ':' + l.port : '') +
                  l.pathname.split('/').slice(0, 1 + pathSegmentsToKeep).join('/') + '/?/' +
                  l.pathname.split('/').slice(1 + pathSegmentsToKeep).join('/').replace(/&/g, '~and~') +
                  (l.search ? '&' + l.search.slice(1).replace(/&/g, '~and~') : '') +
                  l.hash
                );
              </script>
            </head>
            <body>
              <h2>Redirecting...</h2>
            </body>
          </html>
          EOL
      
      # Update index.html for SPA routing
      - name: Update index.html for SPA
        run: |
          sed -i '/<head>/a \
          <!-- Start Single Page Apps for GitHub Pages --> \
          <script type="text/javascript"> \
            (function(l) { \
              if (l.search[1] === "/" ) { \
                var decoded = l.search.slice(1).split("&").map(function(s) { \
                  return s.replace(/~and~/g, "&"); \
                }).join("?"); \
                window.history.replaceState(null, null, \
                    l.pathname.slice(0, -1) + decoded + l.hash \
                ); \
              } \
            }(window.location)) \
          </script> \
          <!-- End Single Page Apps for GitHub Pages -->' ./dist/index.html
      
      # Create a .nojekyll file to prevent Jekyll processing
      - name: Create .nojekyll file
        run: touch ./dist/.nojekyll
        
      # Add stronger cache-busting measures to index.html
      - name: Add strong cache-busting markers
        run: |
          # Add timestamp with nanoseconds precision to ensure uniqueness
          UNIQUE_ID="${{ github.sha }}_${{ github.run_number }}_$(date +%s%N)"
          echo "<!-- Deploy timestamp: $UNIQUE_ID - $(date) -->" >> ./dist/index.html
          
          # Add cache busting meta tag
          sed -i '/<head>/a \
          <meta name="deploy-version" content="'${UNIQUE_ID}'">' ./dist/index.html
          
          # Add cache control headers
          echo 'Cache-Control: no-cache, no-store, must-revalidate' > ./dist/_headers
          echo 'Pragma: no-cache' >> ./dist/_headers
          echo 'Expires: 0' >> ./dist/_headers
        
      # Forcefully clear any previous cache by removing the gh-pages branch first if it exists
      - name: Remove gh-pages branch if it exists
        continue-on-error: true
        run: |
          git push origin --delete gh-pages || echo "No gh-pages branch to delete"
        
      # Deploy with enhanced options to ensure changes take effect
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
          clean: true
          clean-exclude: |
            .nojekyll
            _headers
          single-commit: true
          force: true
          commit-message: "Deploy website with ultra cache buster: ${{ env.DEPLOY_TIMESTAMP }}"

      # Verify deployment status
      - name: Verify deployment
        run: |
          echo "Deployment completed at $(date)"
          echo "Cache buster: ${{ env.DEPLOY_TIMESTAMP }}"
          echo "GitHub SHA: ${{ github.sha }}"
          echo "Run number: ${{ github.run_number }}"
          echo "Full unique ID: ${{ github.sha }}_${{ github.run_number }}_${{ env.DEPLOY_TIMESTAMP }}"
